version: "3.8"

services:
  dev-mysql:
    build:
      context: ../dev-mysql/
    image: dev-mysql
    container_name: dev-mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: r00t123!+
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - dev-network

  dev-ldap-apache-server:
    build:
      context: ../dev-ldap-apache-server/
    image: dev-ldap-apache-server
    container_name: dev-ldap-apache-server
    restart: always
    environment:
      VALID_APP_NAME: valid-oauth2
      VALID_MYSQL_HOSTNAME: valid-mysql
    ports:
      - 10389:10389
    networks:
      - dev-network

  dev-sonarqube-server:
    image: sonarqube:8.3-community
    container_name: dev-sonarqube-server
    restart: always
    ports:
      - 9000:9000
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge
